// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "HearMeOut",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "HearMeOut",
            targets: ["AppModule"],
            bundleIdentifier: "sam1ch.HearMeOut",
            teamIdentifier: "DA7SC56XUA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Hear Me Out uses the camera to track your eye contact and provide feedback on your visual engagement during speaking practice"),
                .speechRecognition(purposeString: "Hear Me Out uses speech recognition to convert your spoken words into text and evaluate your pronunciation and speaking accuracy"),
                .microphone(purposeString: "Hear Me Out uses the microphone to capture your speech and analyze your pronunciation and speaking performance")
            ],
            appCategory: .entertainment
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.version("6")]
)
